
# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build with maven
    runs-on:
      - self-hosted
      - Linux

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: '8'
      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

  docker-build:
    runs-on:
      - self-hosted
      - Linux
    timeout-minutes: 15
    needs: build
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Ahtaaja
        uses: docker/login-action@v1
        with:
          registry: ahtaaja.saunalahti.fi
          username: ${{ secrets.AHTAAJA_USERNAME }}
          password: ${{ secrets.AHTAAJA_PASSWORD }}

      - name: Define image meta
        id: docker_meta
        uses: elisa-actions/ghaction-docker-meta@v2
        with:
          images: ahtaaja.saunalahti.fi/jpd/devel/demo-project
          flavor: |
            latest=true
          tags: |
            type=raw,value=sha-${{ github.sha }}
          labels: |
            org.opencontainers.image.authors=SoSe/SRE
            org.opencontainers.image.vendor=Elisa
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          no-cache: false
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          build-args: |
            COMMIT_SHA=${{ github.sha }}
      - name: Notify failure
        if: failure()
        env:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          MATTERMOST_TEXT: "${{ github.repository }} [${{ github.event.ref }}](${{ github.event.repository.html_url }}/tree/${{ github.event.ref }}) build failed."
        run: |
          send-to-mattermost
